[workspace]
resolver = "2"
members = [
    "protos",
    "common",
    "bundles_server",
    "p2c_server",
]

[workspace.package]
version = "0.1.0"
authors = ["Rakurai"]
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
anyhow = "1.0.102"
bs58 = { version = "0.5.1", default-features = false }
bytes = "1.12.0"
chrono = { version = "0.4.45", default-features = false }
clap = { version = "4.5.31", features = ["derive", "env"] }
dashmap = "5.5.3"
env_logger = "0.11.10"
log = "0.4.32"
prost = "0.14.4"
prost-types = "0.14.4"
protobuf-src = "1.1.0"
rand = "0.9.4"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3.3"
solana-hash = { version = "4.2.0", default-features = false }
solana-keypair = { version = "3.1.2", default-features = false }
solana-message = { version = "4.4.1", default-features = false }
solana-pubkey = { version = "4.2.0", default-features = false }
solana-rpc-client = { version = "4.2.2", default-features = false }
solana-signature = { version = "3.4.1", default-features = false }
solana-signer = { version = "3.0.1", default-features = false }
solana-system-interface = { version = "2.0.0", default-features = false, features = ["bincode"] }
solana-transaction = { version = "4.1.6", default-features = false, features = ["serde", "std", "wincode"] }
tokio = "1.52.3"
tokio-stream = "0.1.18"
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
uuid = { version = "1.26.1", features = ["v4"] }

protos = { path = "protos" }
common = { path = "common" }
